apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-07-14T10:19:41Z"
  labels:
    app: demo
  name: demo
  namespace: default
  resourceVersion: "107479"
  uid: 493a4df7-075c-43ee-8ee5-db1f556d9814
spec:
  clusterIP: 10.107.8.152
  clusterIPs:
  - 10.107.8.152
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
